### PR TITLE
Add hooks for providing alternative items, subjects, and thumbnail images

### PR DESCRIPTION
**Pull request by irace**
Adds hooks for providing alternative items, subjects, and thumbnail images on a per-activity type basis. Addresses the following tickets:

* https://github.com/tumblr/XExtensionItem/issues/33
* https://github.com/tumblr/XExtensionItem/issues/35

I’m going to punt on updating the README for now since I want to do a [bigger pass at rewriting it for 1.0](https://github.com/tumblr/XExtensionItem/issues/32).

Other requests which have been broken out into separate issues:

* https://github.com/tumblr/XExtensionItem/issues/40
* https://github.com/tumblr/XExtensionItem/issues/41

### CODE REVIEW

**Comment by AriX** [comment]
It seems potentially confusing that there is a method called `-registerItemProvider`, but the type of the object you provide is not `NSItemProvider`. In fact, I think it wouldn't even work if you gave it an `NSItemProvider`, correct?

Perhaps it could be called an itemGenerator? Or an itemBlock? Those don't sound especially good but I do think this is a legitimate problem.

**Comment by irace** [comment]
> Those don't sound especially good but I do think this is a legitimate problem.

Yeah, good call. I wonder if this is a premature optimization and if the method should just be called `- (void)registerItem:activityType:` and take an `id`.

If only Objective-C had `@autoclosure` :rage2:

**Comment by AriX** [comment]
Definitely wouldn't call it a premature optimization. We actually rely on asynchronous and conditional item generation, for example, when you share a workflow (so that it's not uploaded to our servers until an activity is chosen, and the text passed varies based on the activity).

I think we should be sensitive as to not do anything that would prevent people from replacing their existing UIActivityViewController implementations with XExtensionItem. If you can't asynchronously generate URLs et al, that could exclude potential users.

**Comment by irace** [comment]
How about:

```objc
- (void)registerItemProvidingBlock:(XExtensionItemProvidingBlock)itemBlock forActivityType:(NSString *)activityType;

- (void)registerThumbnailProvidingBlock:(XExtensionItemThumbnailProvidingBlock)thumbnailBlock forActivityType:(NSString *)activityType;
```

**Comment by AriX** [comment]
That sounds great.

**Comment by prendio2** [comment]
It would be helpful to be able to set a default subject instead of having to account for each service that might use the subject. For example Messages app uses this if you enable subjects on messages but I didn't realize that until just now.

**Comment by irace** [comment]
> It would be helpful to be able to set a default subject instead of having to account for each service that might use the subject. For example Messages app uses this if you enable subjects on messages but I didn't realize that until just now.

Great point – I think we can add a `defaultSubject` property without having it bloat the API too much.

**Comment by prendio2** [comment]
Unless I'm missing something, to provide different `attributedContentText` to different services I would call `- (void)registerItemProvidingBlock:(XExtensionItemProvidingBlock)itemBlock forActivityType:(NSString *)activityType;` for each service I want to customize and return an adjusted `NSExtensionItem`? Would it make sense to be able to just register custom titles/contentText so that the creation of the `NSExtensionItem` remains internal to `XExtensionItem`?

**Comment by irace** [comment]
> Would it make sense to be able to just register custom titles/contentText so that the creation of the NSExtensionItem remains internal to XExtensionItem?

Yes, probably. On one hand, I’m hesitant to add more API that is really only specific to Twitter (and may only be specific to Twitter temporarily, since one would assume they will add their own share extension at some point?). But it’s a very valid point. I’ve created a separate ticket for this in the interest of getting this pull request merged in sooner rather than later: https://github.com/tumblr/XExtensionItem/issues/40

**Comment by irace** [comment]
This should be good to go :pray:

**Pull request merged**
