### PR TITLE
Add a framework target (and as such, Carthage support)

### PR DESCRIPTION
**Pull request by irace**
https://github.com/tumblr/XExtensionItem/issues/42

Diverge from the traditional `pod lib create` project structure in order to add first class framework support.

* `XExtensionItem.xcodeproj` in the root directory now has a framework target and the tests target.
* `Example/XExtensionItemExample.xcworkspace` contains a sample application and share extension, and pulls XExtensionItem in as a development pod

Also fixes a bug in `XExtensionItem.m` and updates the unit tests such that they will fail if it returns.

## To test

* Verify that the framework target builds without any warnings or errors, and that tests all pass
* Verify that the sample application and share extension function as expected
* Verify that a sample project is able to consume XExtensionItem via [Carthage](https://github.com/carthage/carthage)
    * Clone the [CarthageTest](https://github.com/irace/CarthageTest) project locally (it won’t build until the following steps are completed)
    * `brew install carthage`
    * From the `CarthageTest` directory, run `carthage update`
    * Follow [these instructions from the Carthage README](https://github.com/carthage/carthage#if-youre-building-for-ios)
    * Verify that CarthageTest builds properly

### CODE REVIEW

**Comment by mattbischoff** [comment]
Good for me to take a look?

**Comment by irace** [comment]
> Good for me to take a look?

Yes! This is good to go.

**Comment by mattbischoff** [comment]
After following your testing instructions I got this in the console when running `carthage update`:

```
A shell task failed with exit code 65:
2015-05-14 14:57:44.657 xcodebuild[45265:13897135] [MT] PluginLoading: Required plug-in compatibility UUID 9F75337B-21B4-4ADC-B558-F9CADF7073A7 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/BTGisterPost-Xcode5.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2015-05-14 14:57:44.658 xcodebuild[45265:13897135] Failed to load plugin at: /Users/matthew/Library/Application Support/Developer/Shared/Xcode/Plug-ins/BTGisterPost-Xcode5.xcplugin, skipping.  Reason for failure: *** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[0]
2015-05-14 14:57:44.658 xcodebuild[45265:13897135] [MT] PluginLoading: Required plug-in compatibility UUID 9F75337B-21B4-4ADC-B558-F9CADF7073A7 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/BBUFullIssueNavigator.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2015-05-14 14:57:44.798 xcodebuild[45265:13897135] [MT] iPhoneSimulator: SimVerifier returned: Error Domain=NSPOSIXErrorDomain Code=53 "Simulator verification failed." UserInfo=0x7fc9ec0aed80 {NSLocalizedFailureReason=A connection to the simulator verification service could not be established., NSLocalizedRecoverySuggestion=Ensure that Xcode.app is installed on a volume with ownership enabled., NSLocalizedDescription=Simulator verification failed.}
** BUILD FAILED **


The following build commands failed:
	CompileC /Users/matthew/Library/Developer/Xcode/DerivedData/XExtensionItem-dwtsvlbeneczqqcxqptwbapdeqbm/Build/Intermediates/XExtensionItem.build/Release-iphoneos/XExtensionItem.build/Objects-normal/armv7/XExtensionItemTumblrParameters.o XExtensionItem/Custom/Tumblr/XExtensionItemTumblrParameters.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
	CompileC /Users/matthew/Library/Developer/Xcode/DerivedData/XExtensionItem-dwtsvlbeneczqqcxqptwbapdeqbm/Build/Intermediates/XExtensionItem.build/Release-iphoneos/XExtensionItem.build/Objects-normal/armv7/XExtensionItemReferrer.o XExtensionItem/XExtensionItemReferrer.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
	CompileC /Users/matthew/Library/Developer/Xcode/DerivedData/XExtensionItem-dwtsvlbeneczqqcxqptwbapdeqbm/Build/Intermediates/XExtensionItem.build/Release-iphoneos/XExtensionItem.build/Objects-normal/armv7/XExtensionItemTypeSafeDictionaryValues.o XExtensionItem/XExtensionItemTypeSafeDictionaryValues.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
	CompileC /Users/matthew/Library/Developer/Xcode/DerivedData/XExtensionItem-dwtsvlbeneczqqcxqptwbapdeqbm/Build/Intermediates/XExtensionItem.build/Release-iphoneos/XExtensionItem.build/Objects-normal/armv7/XExtensionItem.o XExtensionItem/XExtensionItem.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(4 failures)
```

**Comment by irace** [comment]
@mattbischoff Not sure what the error above what but I fixed the error we just saw at your desk (was caused by [a typo](https://github.com/tumblr/XExtensionItem/commit/ebf592069b36fb84ec29cd0cd35902c224722fa1))

**Comment by mattbischoff** [comment]
alright, will try again

**Comment by irace** [comment]
@mattbischoff I neglected to include a few steps from the Carthage README. Please follow these instructions as well (PR description updated): https://github.com/carthage/carthage#if-youre-building-for-ios

**Comment by mattbischoff** [comment]
Going to merge this guy.

**Pull request merged**
